import { jsPDF } from "jspdf";

export interface DashboardPdfData {
  generatedAt: Date;
  riskScore: number;
  expectedAnnualLoss: string;
  financialExposure: string;
  totalAssets: string;
  criticalVulnerabilities: string;
  topRisks: { risk: string; asset: string; impact: string; likelihood: string; priority: string }[];
}

/** Generates a one-page executive risk summary PDF and triggers a download. */
export function exportDashboardPdf(data: DashboardPdfData) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const marginX = 48;
  let y = 56;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("CyberGuard AI — Executive Risk Summary", marginX, y);
  y += 20;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Generated ${data.generatedAt.toLocaleString("en-IN")}`, marginX, y);
  y += 30;

  doc.setTextColor(20);
  const kpis: [string, string][] = [
    ["Overall Risk Score", `${data.riskScore} / 100`],
    ["Expected Annual Loss", data.expectedAnnualLoss],
    ["Financial Risk Exposure", data.financialExposure],
    ["Total Assets", data.totalAssets],
    ["Critical Vulnerabilities", data.criticalVulnerabilities],
  ];
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("Key Metrics", marginX, y);
  y += 18;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  for (const [label, value] of kpis) {
    doc.text(label, marginX, y);
    doc.text(value, marginX + 220, y);
    y += 18;
  }
  y += 16;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("Top Risk Register", marginX, y);
  y += 20;

  const headers = ["Risk", "Asset", "Impact", "Likelihood", "Priority"];
  const colX = [marginX, marginX + 150, marginX + 280, marginX + 350, marginX + 440];
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  headers.forEach((h, i) => doc.text(h, colX[i], y));
  y += 14;
  doc.setDrawColor(200);
  doc.line(marginX, y - 10, 547, y - 10);

  doc.setFont("helvetica", "normal");
  for (const risk of data.topRisks) {
    doc.text(risk.risk.slice(0, 24), colX[0], y);
    doc.text(risk.asset.slice(0, 18), colX[1], y);
    doc.text(risk.impact, colX[2], y);
    doc.text(risk.likelihood, colX[3], y);
    doc.text(risk.priority, colX[4], y);
    y += 16;
  }

  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text("Generated by CyberGuard AI — demo data for illustration.", marginX, 800);

  doc.save(`cyberguard-executive-summary-${data.generatedAt.toISOString().slice(0, 10)}.pdf`);
}
